lib/todo_app_web/router.ex
defmodule TodoAppWeb.Router do
  use TodoAppWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug TodoAppWeb.Plug.SetUser
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", TodoAppWeb do
    pipe_through :browser
    
    get "/", TarefaController, :index

    # post "/", TarefaController, :create
    # get "/new", TarefaController, :new
    # get "/:id/edit", TarefaController, :edit
    # put "/:id", TarefaController, :update
    # delete "/:id", TarefaController, :delete

    resources "/", TarefaController
  end

  scope "/auth", TodoAppWeb do
    pipe_through :browser

    get "/:provider", AuthController, :request
    get "/:provider/callback", AuthController, :callback
    get "/:provider/logout", AuthController, :logout
  end

  # Other scopes may use custom stacks.
  # scope "/api", TodoAppWeb do
  #   pipe_through :api
  # end
end

lib/todo_app/application.ex
defmodule TodoApp.Application do
  # See https://hexdocs.pm/elixir/Application.html
  # for more information on OTP Applications
  @moduledoc false

  use Application

  def start(_type, _args) do
    # List all child processes to be supervised
    children = [
      # Start the Ecto repository
      TodoApp.Repo,
      # Start the endpoint when the application starts
      TodoAppWeb.Endpoint
      # Starts a worker by calling: TodoApp.Worker.start_link(arg)
      # {TodoApp.Worker, arg},
    ]

    # See https://hexdocs.pm/elixir/Supervisor.html
    # for other strategies and supported options
    opts = [strategy: :one_for_one, name: TodoApp.Supervisor]
    Supervisor.start_link(children, opts)
  end

  # Tell Phoenix to update the endpoint configuration
  # whenever the application is updated.
  def config_change(changed, _new, removed) do
    TodoAppWeb.Endpoint.config_change(changed, removed)
    :ok
  end
end

lib/todo_app/repo.ex
defmodule TodoApp.Repo do
  use Ecto.Repo,
    otp_app: :todo_app,
    adapter: Ecto.Adapters.Postgres
end

lib/todo_app/seguranca/usuario.ex
defmodule TodoApp.Usuario do
    use Ecto.Schema
    import Ecto.Changeset
    alias TodoApp.Tarefa

    schema "usuarios" do
        field :nome, :string
        field :email, :string
        field :token, :string
        field :provider, :string
        has_many :tarefas, Tarefa
        timestamps()
    end

    def changeset(struct, params \\ %{}) do
        struct
        |> cast(params, [:nome, :email, :token, :provider])
        |> validate_required([:nome, :email, :token, :provider])
    end

end

lib/todo_app/tarefa/tarefa.ex
defmodule TodoApp.Tarefa do
    use Ecto.Schema
    import Ecto.Changeset
    alias TodoApp.Usuario

    schema("tarefas") do
        field :titulo, :string
        field :pronto, :boolean
        belongs_to :usuario, Usuario
    end

    def changeset(struct, params \\ %{}) do
        struct
        |> cast(params, [:titulo, :pronto]) # cast para a estrutura de salvar
        |> validate_required([:titulo, :pronto]) # adicionar validacoes
    end
end

lib/todo_app_web/controllers/auth_controller.ex
defmodule TodoAppWeb.AuthController do
    use TodoAppWeb, :controller
    alias TodoApp.{Usuario, Repo}
    plug Ueberauth
    
    def callback(%{assigns: %{ueberauth_auth: auth}} = conn, %{"provider" => provider}) do
        usuario = %{nome: auth.info.name, email: auth.info.email, token: auth.credentials.token, provider: provider}
        changeset = Usuario.changeset(%Usuario{}, usuario)
        logar conn, changeset
    end

    def logout(conn, _param) do
        conn
        |> configure_session(drop: true)
        |> redirect(to: Routes.tarefa_path(conn, :index))
    end

    defp logar(conn, changeset) do
        case insere_ou_busca(changeset) do
            {:ok, usuario} ->
                conn
                |> put_flash(:info, "Bem Vindo!! #{usuario.nome}")
                |> put_session(:user_id, usuario.id)
                |> redirect(to: Routes.tarefa_path(conn, :index))
            {:error, razao} ->
                IO.inspect razao
                conn
                |> put_flash(:error, "Houve um problema na requisição")
                |> redirect(to: Routes.tarefa_path(conn, :index))
        end
    end

    defp insere_ou_busca(changeset) do
        case Repo.get_by(Usuario, email: changeset.changes.email) do
            nil -> Repo.insert changeset
            usuario -> {:ok, usuario}
        end

    end

end

lib/todo_app_web/controllers/tarefa_controller.ex
defmodule TodoAppWeb.TarefaController do
  use TodoAppWeb, :controller

  alias TodoApp.Tarefa
  alias TodoApp.Repo

  plug TodoAppWeb.Plug.RequireAuth when action in [:create, :update, :edit, :delete, :new]
  plug :verifica_permissao when action in [:update, :edit, :delete]

  def index(conn, _param) do
    render conn, "index.html", tarefas: Repo.all(Tarefa)
  end

  def new(conn, _param) do
    changeset = Tarefa.changeset %Tarefa{}
    render conn, "new.html", changeset: changeset
  end
  
  def create(conn, %{"tarefa" => tarefa}) do
    changeset =
    conn.assigns.user
    |> Ecto.build_assoc(:tarefas)
    |> Tarefa.changeset(tarefa)

    case Repo.insert changeset do
      {:ok, struct} ->
        conn
        |> put_flash(:info, "Tarefa incluida na lista")
        |> redirect to: Routes.tarefa_path( conn, :index)
      {:error, changeset} -> render conn, "new.html", changeset: changeset
    end
    render conn, "index.html"
  end

  def edit(conn, %{"id" => tarefa_id}) do
    tarefa = Repo.get(Tarefa, tarefa_id)
    changeset = Tarefa.changeset(tarefa)
    render conn, "edit.html", changeset: changeset, tarefa: tarefa
  end

  def update(conn, %{"tarefa" => tarefa, "id" => id}) do
    tarefa_alterar = Repo.get(Tarefa, id)
    changeset = Tarefa.changeset(tarefa_alterar, tarefa)
    case Repo.update changeset do
      {:ok, struct} ->
        conn
        |> put_flash(:info, "Tarefa #{id} Atualizada")
        |> redirect to: Routes.tarefa_path conn, :index
      {:error, changeset} -> 
        render conn, "edit.html", changeset: changeset, tarefa: tarefa
    end
  end

  def delete(conn, %{"id" => id}) do
    Repo.get!(Tarefa, id)
    |> Repo.delete!

    conn
    |> put_flash(:info, "Tarefa deletada")
    |> redirect to: Routes.tarefa_path conn, :index
  end

  def verifica_permissao(conn, _params) do
    %{params: %{"id" => tarefa_id}} = conn

    if Repo.get(Tarefa, tarefa_id).usuario_id == conn.assigns.user.id do
      conn
    else
      conn
      |> put_flash(:error, "Essa tarefa não é sua.")
      |> redirect(to: Routes.tarefa_path(conn, :index))
      |> halt
    end
  end

end

lib/todo_app_web/views/error_view.ex
defmodule TodoAppWeb.ErrorView do
  use TodoAppWeb, :view

  # If you want to customize a particular status code
  # for a certain format, you may uncomment below.
  # def render("500.html", _assigns) do
  #   "Internal Server Error"
  # end

  # By default, Phoenix returns the status message from
  # the template name. For example, "404.html" becomes
  # "Not Found".
  def template_not_found(template, _assigns) do
    Phoenix.Controller.status_message_from_template(template)
  end
end

lib/todo_app_web/views/layout_view.ex
defmodule TodoAppWeb.LayoutView do
  use TodoAppWeb, :view
end

lib/todo_app_web/views/tarefa_view.ex
defmodule TodoAppWeb.TarefaView do
    use TodoAppWeb, :view
end

lib/todo_app_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>TodoApp · Phoenix Framework</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css"> 
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>"/>
  </head>
  <body>
    <header>
      <nav class="blue">
        <div class="nav-wrapper">
          <a href="/" class="brand-logo">Todo List</a>
          <ul id="nav-mobile" class="right hide-on-med-and-down">
            <%= if @conn.assigns[:user] do %>
              <li><%= gettext "Olá, %{nome} |", nome: @conn.assigns.user.nome %></li>
              <li><%= link "Sair", to: Routes.auth_path(@conn, :logout, "github") %></li>
            <%= else %>
              <li><%= link "Entrar", to: Routes.auth_path(@conn, :request, "github") %></li>
            <% end %>
          </ul>
        </div>
      </nav>
    </header>
    <main role="main" class="container">
      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
      <%= render @view_module, @view_template, assigns %>
    </main>
    <script type="text/javascript" src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>

lib/todo_app_web/templates/tarefa/edit.html.eex
<h3>Editar tarefa</h3>

<%= form_for @changeset, Routes.tarefa_path(@conn, :update, @tarefa), fn f -> %>
  <div class="form-group col-md-8">
    <%= text_input f, :titulo, placeholder: "Título", class: "form-control col-md-6" %>
    <%= error_tag f, :titulo %>
    <%= select f, :pronto, [true, false], class: "form-control col-md-6", style: "display: block", prompt: "Tarefa finalizada?" %>
    <%= error_tag f, :pronto %>
  </div>
  <%= submit "Salvar", class: "btn btn-primary"%>
<% end %>

lib/todo_app_web/templates/tarefa/index.html.eex
<%= if @conn.assigns[:user] do %>
<h3>Listagem de tarefas</h3>

 <table class="centered">
  <thead>
    <tr>
      <th>Título</th>
      <th>Pronto?</th>
      <th>Ações</th>
    </tr>
  </thead>

  <tbody>
    <%= for tarefa <- @tarefas do %>
    <%= if @conn.assigns.user.id == tarefa.usuario_id do %>
      <tr>
        <td><%= tarefa.titulo %></td>
        <td><%= tarefa.pronto %></td>
        <td class="secondary-content"><%= link  to: Routes.tarefa_path(@conn, :edit, tarefa) do %>
          <i class="material-icons">edit</i>
        <% end %>
        <%= link  to: Routes.tarefa_path(@conn, :delete, tarefa), method: :delete do %>
          <i class="material-icons">delete</i>
        <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<div class="fixed-action-btn">
  <%= link to: "/new", class: "btn-floating wavrs-effect waves-light red" do %>
    <i class="material-icons">add</i>
  <% end %>
</div>
<% end %>
<% else %>

<p>Click em Entrar para visualizar as tarefas</p>

<% end %>

lib/todo_app_web/templates/tarefa/new.html.eex
<h3>Nova tarefa</h3>

<%= form_for @changeset, Routes.tarefa_path(@conn, :create), fn f ->%>
  <div class="form-group col-md-8">
    <%= text_input f, :titulo, placeholder: "Título", class: "form-control col-md-6" %>
    <%= error_tag f, :titulo %>
    <%= select f, :pronto, [true, false], class: "form-control col-md-6", style: "display: block", prompt: "Tarefa finalizada?" %>
    <%= error_tag f, :pronto %>
  </div>
  <%= submit "Salvar", class: "btn btn-primary"%>
<% end %>

lib/todo_app_web/templates/tarefa/show.html.eex
<p>Salvou</p>

<%= "Título: #{@tarefa["titulo"]}" %>
</br>
<%= "Pronto: #{@tarefa["pronto"]}" %>